export enum ORDER_STATUS {
  PENDING = 'PENDING',
  CREATED = 'CREATED',
  RECEIVED = 'RECEIVED',
  READY = 'READY',
  IN_DELIVERY = 'IN_DELIVERY',
  DELIVERED = 'DELIVERED',
  FINISHED = 'FINISHED',
  CANCELED_DELIVERYMAN = 'CANCELED_DELIVERYMAN',
  CANCELED_STORE = 'CANCELED_STORE',
}
