export const DATA_SOURCE = 'DATA_SOURCE';
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const ORDER_REPOSITORY = 'ORDER_REPOSITORY';
export const DELIVERYMAN_REPOSITORY = 'DELIVERYMAN_REPOSITORY';
export const STORE_REPOSITORY = 'STORE_REPOSITORY';
export const DELIVERYMAN_SOCKETS = 'DELIVERYMAN_SOCKETS';
export const API_KEY = 'API_KEY';
